name: CI workflow for backend

on: push
  # push:
  #   paths:
  #     - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      
      - name: Test backend
        run: |
          cd backend
          ./gradlew test

  build-and-push-backend:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Build bootJar
        run: |
          cd backend
          ./gradlew bootJar

      - name: Build Image and Deploy
        uses: ./.github/workflows/build-deploy.yml
        with:
          folder: backend
          image_name: booking-backend
          deployment_name: booking-backend
