name: Reusable workflow to build and deploy

on: 
  workflow_call:
    inputs:
      folder:
        required: true
        type: string
      image_name:
        required: true
        type: string
      deployment_name:
        required: true
        type: string

env:
  PROJECT_ID: pivot-lab-2203
  GKE_CLUSTER: booking-app-cluster
  GKE_ZONE: us-west1
  DOCKER_REGISTRY: us-west1-docker.pkg.dev/pivot-lab-2203/docker-image-repo

jobs:
  build-image-and-push:
    runs-on: ubuntu-latest
    steps:
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_SA_CREDENTIALS }}'
          token_format: access_token

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: oauth2accesstoken
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Build and push image to artifact registry
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.folder }}
          file: ${{ inputs.folder }}/Dockerfile
          push: true
          tags:  ${{ env.DOCKER_REGISTRY }}/${{ inputs.image_name }}:latest

  update-image:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_SA_CREDENTIALS }}'
          token_format: access_token

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id:  ${{ env.PROJECT_ID }}
          install_components: kubectl

      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      
      - name: Deploy
        run: |-
          kubectl rollout restart deployment ${{ inputs.deployment_name }}
          kubectl rollout status deployment ${{ inputs.deployment_name }}

