name: CI

on: push

env:
  PROJECT_ID: pivot-lab-2203
  GKE_CLUSTER: booking-app-cluster
  GKE_ZONE: us-west1
  DOCKER_REGISTRY: us-west1-docker.pkg.dev/pivot-lab-2203/docker-image-repo

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      
      - name: Test backend
        run: |
          cd backend
          ./gradlew test

  build-and-push-backend:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    needs: test-backend
    steps:
      - uses: actions/checkout@v3
      
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_SA_CREDENTIALS }}'
          token_format: access_token

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: oauth2accesstoken
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Build bootJar
        run: |
          cd backend
          ./gradlew bootJar

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          tags:  ${{ env.DOCKER_REGISTRY }}/booking-backend:latest

  build-and-push-frontend:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    steps:
      - uses: actions/checkout@v3
      
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_SA_CREDENTIALS }}'
          token_format: access_token

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: oauth2accesstoken
          password: '${{ steps.auth.outputs.access_token }}'
      
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: booking-system-ui
          file: booking-system-ui/Dockerfile
          push: true
          tags:  ${{ env.DOCKER_REGISTRY }}/booking-frontend:latest

  rollout-frontend:
    runs-on: ubuntu-latest
    needs: [build-and-push-backend, build-and-push-frontend]
    steps:
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_SA_CREDENTIALS }}'
          token_format: access_token

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id:  ${{ env.PROJECT_ID }}
          install_components: kubectl

      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      
      - name: Rollout
        run: |-
          kubectl rollout restart deployment booking-frontend
          kubectl rollout status deployment booking-frontend

  rollout-backend:
    runs-on: ubuntu-latest
    needs: [build-and-push-backend, build-and-push-frontend]
    steps:
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_SA_CREDENTIALS }}'
          token_format: access_token

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id:  ${{ env.PROJECT_ID }}
          install_components: kubectl

      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      
      - name: Rollout
        run: |-
          kubectl rollout restart deployment booking-backend
          kubectl rollout status deployment booking-backend
